@{
    SourceFiles = @(
        'src/App/Bootstrap.ps1'
        'src/Config/AppConfig.ps1'
        'src/Infrastructure/JsonStore.ps1'
        'src/Domain/HudModel.ps1'
        'src/UI/HudMonitor.ps1'
        'src/UI/HudControls.ps1'
        'src/UI/HudRuntime.ps1'
        'src/UI/HudSnippets.ps1'
        'src/UI/HudPanelLayout.ps1'
        'src/UI/HudFavorites.ps1'
        'src/UI/HudRecent.ps1'
        'src/UI/HudInput.ps1'
        'src/UI/HudEditorView.ps1'
        'src/UI/MainWindow.ps1'
        'src/App/Run.ps1'
    )
}
